/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Department } from '../../models/department';
import { DepartmentWrite } from '../../models/department-write';

export interface CreateDepartment$Params {

/**
 * Stable per user intent; reused on retry of the same intent
 */
  'Idempotency-Key': string;
      body: DepartmentWrite
}

export function createDepartment(http: HttpClient, rootUrl: string, params: CreateDepartment$Params, context?: HttpContext): Observable<StrictHttpResponse<Department>> {
  const rb = new RequestBuilder(rootUrl, createDepartment.PATH, 'post');
  if (params) {
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Department>;
    })
  );
}

createDepartment.PATH = '/v1/departments';
