/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Department } from '../../models/department';
import { DepartmentWrite } from '../../models/department-write';

export interface UpdateDepartment$Params {
  departmentId: string;

/**
 * ETag from the last read; stale values get 412
 */
  'If-Match': string;
      body: DepartmentWrite
}

export function updateDepartment(http: HttpClient, rootUrl: string, params: UpdateDepartment$Params, context?: HttpContext): Observable<StrictHttpResponse<Department>> {
  const rb = new RequestBuilder(rootUrl, updateDepartment.PATH, 'patch');
  if (params) {
    rb.path('departmentId', params.departmentId, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Department>;
    })
  );
}

updateDepartment.PATH = '/v1/departments/{departmentId}';
