/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReceiptUploadRequest } from '../../models/receipt-upload-request';
import { ReceiptUploadSlot } from '../../models/receipt-upload-slot';

export interface CreateReceiptUpload$Params {
  claimId: string;

/**
 * Stable per user intent; reused on retry of the same intent
 */
  'Idempotency-Key': string;
      body: ReceiptUploadRequest
}

export function createReceiptUpload(http: HttpClient, rootUrl: string, params: CreateReceiptUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<ReceiptUploadSlot>> {
  const rb = new RequestBuilder(rootUrl, createReceiptUpload.PATH, 'post');
  if (params) {
    rb.path('claimId', params.claimId, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReceiptUploadSlot>;
    })
  );
}

createReceiptUpload.PATH = '/v1/claims/{claimId}/receipts/upload-url';
