/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeleteClaim$Params {
  claimId: string;

/**
 * ETag from the last read; stale values get 412
 */
  'If-Match': string;
}

export function deleteClaim(http: HttpClient, rootUrl: string, params: DeleteClaim$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteClaim.PATH, 'delete');
  if (params) {
    rb.path('claimId', params.claimId, {});
    rb.header('If-Match', params['If-Match'], {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deleteClaim.PATH = '/v1/claims/{claimId}';
