/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Receipt } from '../../models/receipt';

export interface GetReceipt$Params {
  claimId: string;
  receiptId: string;
}

export function getReceipt(http: HttpClient, rootUrl: string, params: GetReceipt$Params, context?: HttpContext): Observable<StrictHttpResponse<Receipt>> {
  const rb = new RequestBuilder(rootUrl, getReceipt.PATH, 'get');
  if (params) {
    rb.path('claimId', params.claimId, {});
    rb.path('receiptId', params.receiptId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Receipt>;
    })
  );
}

getReceipt.PATH = '/v1/claims/{claimId}/receipts/{receiptId}';
