/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReceiptUploadPolicy } from '../../models/receipt-upload-policy';

export interface GetReceiptUploadPolicy$Params {
}

export function getReceiptUploadPolicy(http: HttpClient, rootUrl: string, params?: GetReceiptUploadPolicy$Params, context?: HttpContext): Observable<StrictHttpResponse<ReceiptUploadPolicy>> {
  const rb = new RequestBuilder(rootUrl, getReceiptUploadPolicy.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReceiptUploadPolicy>;
    })
  );
}

getReceiptUploadPolicy.PATH = '/v1/claims/upload-policy';
