/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Claim } from '../../models/claim';

export interface GetClaim$Params {
  claimId: string;
}

export function getClaim(http: HttpClient, rootUrl: string, params: GetClaim$Params, context?: HttpContext): Observable<StrictHttpResponse<Claim>> {
  const rb = new RequestBuilder(rootUrl, getClaim.PATH, 'get');
  if (params) {
    rb.path('claimId', params.claimId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Claim>;
    })
  );
}

getClaim.PATH = '/v1/claims/{claimId}';
