/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClaimStatus } from '../../models/claim-status';
import { ClaimSummaryPage } from '../../models/claim-summary-page';

export interface ListMyClaims$Params {

/**
 * Zero-based page index
 */
  page?: number;
  size?: number;

/**
 * field,asc or field,desc
 */
  sort?: string;
  status?: ClaimStatus;

/**
 * YYYY-MM
 */
  period?: string;
}

export function listMyClaims(http: HttpClient, rootUrl: string, params?: ListMyClaims$Params, context?: HttpContext): Observable<StrictHttpResponse<ClaimSummaryPage>> {
  const rb = new RequestBuilder(rootUrl, listMyClaims.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
    rb.query('status', params.status, {});
    rb.query('period', params.period, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClaimSummaryPage>;
    })
  );
}

listMyClaims.PATH = '/v1/claims';
