/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Claim } from '../../models/claim';

export interface SubmitClaim$Params {
  claimId: string;

/**
 * ETag from the last read; stale values get 412
 */
  'If-Match': string;

/**
 * Stable per user intent; reused on retry of the same intent
 */
  'Idempotency-Key': string;
}

export function submitClaim(http: HttpClient, rootUrl: string, params: SubmitClaim$Params, context?: HttpContext): Observable<StrictHttpResponse<Claim>> {
  const rb = new RequestBuilder(rootUrl, submitClaim.PATH, 'post');
  if (params) {
    rb.path('claimId', params.claimId, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Claim>;
    })
  );
}

submitClaim.PATH = '/v1/claims/{claimId}/submit';
