/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Claim } from '../../models/claim';
import { ClaimWrite } from '../../models/claim-write';

export interface UpdateClaim$Params {
  claimId: string;

/**
 * ETag from the last read; stale values get 412
 */
  'If-Match': string;
      body: ClaimWrite
}

export function updateClaim(http: HttpClient, rootUrl: string, params: UpdateClaim$Params, context?: HttpContext): Observable<StrictHttpResponse<Claim>> {
  const rb = new RequestBuilder(rootUrl, updateClaim.PATH, 'put');
  if (params) {
    rb.path('claimId', params.claimId, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Claim>;
    })
  );
}

updateClaim.PATH = '/v1/claims/{claimId}';
