/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { User } from '../../models/user';
import { UserRolesUpdate } from '../../models/user-roles-update';

export interface SetUserRoles$Params {
  userId: string;

/**
 * ETag from the last read; stale values get 412
 */
  'If-Match': string;
      body: UserRolesUpdate
}

export function setUserRoles(http: HttpClient, rootUrl: string, params: SetUserRoles$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
  const rb = new RequestBuilder(rootUrl, setUserRoles.PATH, 'put');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<User>;
    })
  );
}

setUserRoles.PATH = '/v1/users/{userId}/roles';
