/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TenantPage } from '../../models/tenant-page';
import { TenantStatus } from '../../models/tenant-status';

export interface ListTenants$Params {

/**
 * Zero-based page index
 */
  page?: number;
  size?: number;

/**
 * field,asc or field,desc
 */
  sort?: string;
  q?: string;
  status?: TenantStatus;
}

export function listTenants(http: HttpClient, rootUrl: string, params?: ListTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<TenantPage>> {
  const rb = new RequestBuilder(rootUrl, listTenants.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
    rb.query('q', params.q, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TenantPage>;
    })
  );
}

listTenants.PATH = '/v1/platform/tenants';
