/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Tenant } from '../../models/tenant';

export interface RetryTenantProvisioning$Params {
  tenantId: string;

/**
 * Stable per user intent; reused on retry of the same intent
 */
  'Idempotency-Key': string;
}

export function retryTenantProvisioning(http: HttpClient, rootUrl: string, params: RetryTenantProvisioning$Params, context?: HttpContext): Observable<StrictHttpResponse<Tenant>> {
  const rb = new RequestBuilder(rootUrl, retryTenantProvisioning.PATH, 'post');
  if (params) {
    rb.path('tenantId', params.tenantId, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Tenant>;
    })
  );
}

retryTenantProvisioning.PATH = '/v1/platform/tenants/{tenantId}/provisioning/retry';
