/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SetupStatus } from '../../models/setup-status';

export interface GetSetupStatus$Params {
}

export function getSetupStatus(http: HttpClient, rootUrl: string, params?: GetSetupStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<SetupStatus>> {
  const rb = new RequestBuilder(rootUrl, getSetupStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SetupStatus>;
    })
  );
}

getSetupStatus.PATH = '/v1/organization/setup';
