/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettlementBatch } from '../../models/settlement-batch';
import { SettlementBatchCreate } from '../../models/settlement-batch-create';

export interface CreateSettlementBatch$Params {

/**
 * Stable per user intent; reused on retry of the same intent
 */
  'Idempotency-Key': string;
      body: SettlementBatchCreate
}

export function createSettlementBatch(http: HttpClient, rootUrl: string, params: CreateSettlementBatch$Params, context?: HttpContext): Observable<StrictHttpResponse<SettlementBatch>> {
  const rb = new RequestBuilder(rootUrl, createSettlementBatch.PATH, 'post');
  if (params) {
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettlementBatch>;
    })
  );
}

createSettlementBatch.PATH = '/v1/settlements/batches';
