/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DownloadUrl } from '../../models/download-url';

export interface GetSettlementExportUrl$Params {
  batchId: string;
  exportId: string;
}

export function getSettlementExportUrl(http: HttpClient, rootUrl: string, params: GetSettlementExportUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<DownloadUrl>> {
  const rb = new RequestBuilder(rootUrl, getSettlementExportUrl.PATH, 'get');
  if (params) {
    rb.path('batchId', params.batchId, {});
    rb.path('exportId', params.exportId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DownloadUrl>;
    })
  );
}

getSettlementExportUrl.PATH = '/v1/settlements/batches/{batchId}/exports/{exportId}/download-url';
