/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettlementBatch } from '../../models/settlement-batch';

export interface GetSettlementBatch$Params {
  batchId: string;
}

export function getSettlementBatch(http: HttpClient, rootUrl: string, params: GetSettlementBatch$Params, context?: HttpContext): Observable<StrictHttpResponse<SettlementBatch>> {
  const rb = new RequestBuilder(rootUrl, getSettlementBatch.PATH, 'get');
  if (params) {
    rb.path('batchId', params.batchId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettlementBatch>;
    })
  );
}

getSettlementBatch.PATH = '/v1/settlements/batches/{batchId}';
