/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettlementCandidatePage } from '../../models/settlement-candidate-page';

export interface ListSettlementQueue$Params {

/**
 * Zero-based page index
 */
  page?: number;
  size?: number;

/**
 * field,asc or field,desc
 */
  sort?: string;
}

export function listSettlementQueue(http: HttpClient, rootUrl: string, params?: ListSettlementQueue$Params, context?: HttpContext): Observable<StrictHttpResponse<SettlementCandidatePage>> {
  const rb = new RequestBuilder(rootUrl, listSettlementQueue.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettlementCandidatePage>;
    })
  );
}

listSettlementQueue.PATH = '/v1/settlements/queue';
