/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BatchStatus } from '../../models/batch-status';
import { SettlementBatchSummaryPage } from '../../models/settlement-batch-summary-page';

export interface ListSettlementBatches$Params {

/**
 * Zero-based page index
 */
  page?: number;
  size?: number;

/**
 * field,asc or field,desc
 */
  sort?: string;
  status?: BatchStatus;
}

export function listSettlementBatches(http: HttpClient, rootUrl: string, params?: ListSettlementBatches$Params, context?: HttpContext): Observable<StrictHttpResponse<SettlementBatchSummaryPage>> {
  const rb = new RequestBuilder(rootUrl, listSettlementBatches.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettlementBatchSummaryPage>;
    })
  );
}

listSettlementBatches.PATH = '/v1/settlements/batches';
