/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentEvidenceWrite } from '../../models/payment-evidence-write';
import { SettlementBatch } from '../../models/settlement-batch';

export interface RecordSettlementPayment$Params {
  batchId: string;

/**
 * ETag from the last read; stale values get 412
 */
  'If-Match': string;

/**
 * Stable per user intent; reused on retry of the same intent
 */
  'Idempotency-Key': string;
      body: PaymentEvidenceWrite
}

export function recordSettlementPayment(http: HttpClient, rootUrl: string, params: RecordSettlementPayment$Params, context?: HttpContext): Observable<StrictHttpResponse<SettlementBatch>> {
  const rb = new RequestBuilder(rootUrl, recordSettlementPayment.PATH, 'post');
  if (params) {
    rb.path('batchId', params.batchId, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettlementBatch>;
    })
  );
}

recordSettlementPayment.PATH = '/v1/settlements/batches/{batchId}/payment';
