/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApprovalDecision } from '../../models/approval-decision';
import { ApprovalView } from '../../models/approval-view';

export interface DecideApproval$Params {
  claimId: string;

/**
 * ETag from the last read; stale values get 412
 */
  'If-Match': string;

/**
 * Stable per user intent; reused on retry of the same intent
 */
  'Idempotency-Key': string;
      body: ApprovalDecision
}

export function decideApproval(http: HttpClient, rootUrl: string, params: DecideApproval$Params, context?: HttpContext): Observable<StrictHttpResponse<ApprovalView>> {
  const rb = new RequestBuilder(rootUrl, decideApproval.PATH, 'post');
  if (params) {
    rb.path('claimId', params.claimId, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApprovalView>;
    })
  );
}

decideApproval.PATH = '/v1/approvals/{claimId}/decision';
