/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApprovalView } from '../../models/approval-view';

export interface GetApproval$Params {
  claimId: string;
}

export function getApproval(http: HttpClient, rootUrl: string, params: GetApproval$Params, context?: HttpContext): Observable<StrictHttpResponse<ApprovalView>> {
  const rb = new RequestBuilder(rootUrl, getApproval.PATH, 'get');
  if (params) {
    rb.path('claimId', params.claimId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApprovalView>;
    })
  );
}

getApproval.PATH = '/v1/approvals/{claimId}';
