/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApprovalRoute } from '../../models/approval-route';

export interface GetApprovalRoute$Params {
}

export function getApprovalRoute(http: HttpClient, rootUrl: string, params?: GetApprovalRoute$Params, context?: HttpContext): Observable<StrictHttpResponse<ApprovalRoute>> {
  const rb = new RequestBuilder(rootUrl, getApprovalRoute.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApprovalRoute>;
    })
  );
}

getApprovalRoute.PATH = '/v1/approval-route';
