/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DownloadUrl } from '../../models/download-url';

export interface GetApprovalReceiptUrl$Params {
  claimId: string;
  receiptId: string;
}

export function getApprovalReceiptUrl(http: HttpClient, rootUrl: string, params: GetApprovalReceiptUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<DownloadUrl>> {
  const rb = new RequestBuilder(rootUrl, getApprovalReceiptUrl.PATH, 'get');
  if (params) {
    rb.path('claimId', params.claimId, {});
    rb.path('receiptId', params.receiptId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DownloadUrl>;
    })
  );
}

getApprovalReceiptUrl.PATH = '/v1/approvals/{claimId}/receipts/{receiptId}/download-url';
