/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApprovalTaskPage } from '../../models/approval-task-page';

export interface ListMyApprovals$Params {

/**
 * Zero-based page index
 */
  page?: number;
  size?: number;

/**
 * field,asc or field,desc
 */
  sort?: string;
  state?: 'PENDING' | 'DECIDED';
}

export function listMyApprovals(http: HttpClient, rootUrl: string, params?: ListMyApprovals$Params, context?: HttpContext): Observable<StrictHttpResponse<ApprovalTaskPage>> {
  const rb = new RequestBuilder(rootUrl, listMyApprovals.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
    rb.query('state', params.state, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApprovalTaskPage>;
    })
  );
}

listMyApprovals.PATH = '/v1/approvals';
