/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApprovalRoute } from '../../models/approval-route';
import { ApprovalRouteWrite } from '../../models/approval-route-write';

export interface UpdateApprovalRoute$Params {

/**
 * ETag from the last read; stale values get 412
 */
  'If-Match': string;
      body: ApprovalRouteWrite
}

export function updateApprovalRoute(http: HttpClient, rootUrl: string, params: UpdateApprovalRoute$Params, context?: HttpContext): Observable<StrictHttpResponse<ApprovalRoute>> {
  const rb = new RequestBuilder(rootUrl, updateApprovalRoute.PATH, 'put');
  if (params) {
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApprovalRoute>;
    })
  );
}

updateApprovalRoute.PATH = '/v1/approval-route';
