/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmployeePage } from '../../models/employee-page';
import { EmployeeStatus } from '../../models/employee-status';

export interface ListEmployees$Params {

/**
 * Zero-based page index
 */
  page?: number;
  size?: number;

/**
 * field,asc or field,desc
 */
  sort?: string;

/**
 * Matches name, employee number or email
 */
  q?: string;
  status?: EmployeeStatus;
  departmentId?: string;
}

export function listEmployees(http: HttpClient, rootUrl: string, params?: ListEmployees$Params, context?: HttpContext): Observable<StrictHttpResponse<EmployeePage>> {
  const rb = new RequestBuilder(rootUrl, listEmployees.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
    rb.query('q', params.q, {});
    rb.query('status', params.status, {});
    rb.query('departmentId', params.departmentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmployeePage>;
    })
  );
}

listEmployees.PATH = '/v1/employees';
