/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Employee } from '../../models/employee';
import { EmployeeUpdate } from '../../models/employee-update';

export interface UpdateEmployee$Params {
  employeeId: string;

/**
 * ETag from the last read; stale values get 412
 */
  'If-Match': string;
      body: EmployeeUpdate
}

export function updateEmployee(http: HttpClient, rootUrl: string, params: UpdateEmployee$Params, context?: HttpContext): Observable<StrictHttpResponse<Employee>> {
  const rb = new RequestBuilder(rootUrl, updateEmployee.PATH, 'patch');
  if (params) {
    rb.path('employeeId', params.employeeId, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Employee>;
    })
  );
}

updateEmployee.PATH = '/v1/employees/{employeeId}';
