/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FirstApprover } from '../models/first-approver';
import { Money } from '../models/money';
export interface ApprovalRouteWrite {

  /**
   * Used when the claimant has no manager, or the manager is the claimant
   */
  fallbackApproverUserId: string;
  firstApprover: FirstApprover;

  /**
   * Claims with a total above this need a second approval; null disables it
   */
  secondApprovalAbove?: (Money | null);
  secondApproverUserId?: (string | null);
}
