/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApprovalRouteWrite } from '../models/approval-route-write';
export type ApprovalRoute = ApprovalRouteWrite & {
'fallbackApproverName'?: (string | null);
'secondApproverName'?: (string | null);
'version': number;
};

