/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApprovalDecisionType } from '../models/approval-decision-type';
export interface ApprovalDecision {
  decision: ApprovalDecisionType;

  /**
   * Required for REJECT and REQUEST_CHANGES; shown to the claimant
   */
  reason?: (string | null);
}
