/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApprovalDecisionType } from '../models/approval-decision-type';
import { ClaimStatus } from '../models/claim-status';
import { Money } from '../models/money';
export interface ApprovalTask {
  claimId: string;
  claimNumber: string;
  claimantName: string;
  currency: string;
  decidedAt?: (string | null);
  decision?: (ApprovalDecisionType | null);
  departmentName?: (string | null);
  period: string;
  status: ClaimStatus;
  step: number;
  submittedAt?: (string | null);
  totalAmount: Money;
  totalSteps: number;

  /**
   * Findings the reviewer should look at
   */
  warningCount: number;
}
