/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApprovalTask } from '../models/approval-task';
import { PageMetadata } from '../models/page-metadata';
export interface ApprovalTaskPage {
  content: Array<ApprovalTask>;
  page: PageMetadata;
}
