/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApprovalDecisionType } from './approval-decision-type';

/**
 * Each possible value of `ApprovalDecisionType`
 */
export const APPROVAL_DECISION_TYPE: ApprovalDecisionType[] = [
  'APPROVE',
  'REJECT',
  'REQUEST_CHANGES'
];