/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApprovalDecisionType } from '../models/approval-decision-type';
import { Claim } from '../models/claim';
export interface ApprovalView {

  /**
   * Empty when the signed-in user may not decide (already decided, not assigned, own claim)
   */
  allowedDecisions: Array<ApprovalDecisionType>;
  claim: Claim;
  claimantName: string;
  departmentName?: (string | null);
  step: number;
  totalSteps: number;
}
