/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BatchStatus } from './batch-status';

/**
 * Each possible value of `BatchStatus`
 */
export const BATCH_STATUS: BatchStatus[] = [
  'DRAFT',
  'EXPORT_PENDING',
  'EXPORT_CREATED',
  'EXPORT_FAILED',
  'PAYMENT_RECORDED'
];