/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClaimStatus } from '../models/claim-status';
import { Money } from '../models/money';
export interface ClaimSummary {
  currency: string;
  id: string;
  itemCount: number;
  number: string;
  period: string;
  status: ClaimStatus;
  submittedAt?: (string | null);
  totalAmount: Money;
  updatedAt: string;
}
