/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClaimSummary } from '../models/claim-summary';
import { PageMetadata } from '../models/page-metadata';
export interface ClaimSummaryPage {
  content: Array<ClaimSummary>;
  page: PageMetadata;
}
