/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClaimStatus } from './claim-status';

/**
 * Each possible value of `ClaimStatus`
 */
export const CLAIM_STATUS: ClaimStatus[] = [
  'DRAFT',
  'SUBMITTED',
  'NEEDS_CHANGES',
  'UNDER_REVIEW',
  'APPROVED',
  'REJECTED',
  'READY_FOR_SETTLEMENT',
  'SETTLED'
];