/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Money } from '../models/money';
import { TransportMode } from '../models/transport-mode';
export interface ClaimItemWrite {
  amount: Money;
  fromLocation: string;
  mode: TransportMode;
  purpose?: (string | null);
  receiptId?: (string | null);
  toLocation: string;

  /**
   * Calendar day of the trip; no time zone
   */
  tripDate: string;
}
