/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClaimAction } from '../models/claim-action';
import { ClaimItem } from '../models/claim-item';
import { ClaimStatus } from '../models/claim-status';
import { Money } from '../models/money';
import { PolicyFinding } from '../models/policy-finding';
import { Receipt } from '../models/receipt';
import { TimelineEvent } from '../models/timeline-event';
export interface Claim {
  allowedActions: Array<ClaimAction>;
  currency: string;
  findings: Array<PolicyFinding>;
  id: string;
  items: Array<ClaimItem>;

  /**
   * Human reference, e.g. CLM-2026-0042
   */
  number: string;
  period: string;
  policyId?: (string | null);
  policyVersion?: (number | null);
  receipts: Array<Receipt>;
  status: ClaimStatus;
  submittedAt?: (string | null);
  timeline: Array<TimelineEvent>;
  totalAmount: Money;
  updatedAt: string;
  version: number;
}
