/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClaimItemWrite } from '../models/claim-item-write';
export interface ClaimWrite {
  items: Array<ClaimItemWrite>;

  /**
   * Claim month, YYYY-MM
   */
  period: string;
}
