/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClaimAction } from './claim-action';

/**
 * Each possible value of `ClaimAction`
 */
export const CLAIM_ACTION: ClaimAction[] = [
  'EDIT',
  'SUBMIT',
  'DELETE'
];