/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type ClaimStatus = 'DRAFT' | 'SUBMITTED' | 'NEEDS_CHANGES' | 'UNDER_REVIEW' | 'APPROVED' | 'REJECTED' | 'READY_FOR_SETTLEMENT' | 'SETTLED';

