/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Department {
  employeeCount: number;
  id: string;
  managerId?: (string | null);
  managerName?: (string | null);
  name: string;
  version: number;
}
