/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmployeeCreate } from '../models/employee-create';
import { EmployeeStatus } from '../models/employee-status';
export type EmployeeUpdate = EmployeeCreate & {
'status': EmployeeStatus;
};

