/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EmployeeStatus } from '../models/employee-status';
export interface Employee {
  departmentId?: (string | null);
  departmentName?: (string | null);
  email?: (string | null);

  /**
   * HR identifier, unique within the tenant
   */
  employeeNumber: string;
  fullName: string;
  id: string;
  managerId?: (string | null);
  managerName?: (string | null);
  phone?: (string | null);
  status: EmployeeStatus;

  /**
   * Linked sign-in account; differs from the HR id
   */
  userId?: (string | null);
  version: number;
}
