/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmployeeCreate {
  departmentId?: (string | null);
  email?: (string | null);
  employeeNumber: string;
  fullName: string;
  managerId?: (string | null);
  phone?: (string | null);
}
