/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Employee } from '../models/employee';
import { PageMetadata } from '../models/page-metadata';
export interface EmployeePage {
  content: Array<Employee>;
  page: PageMetadata;
}
