/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FieldError {
  code: string;

  /**
   * Path, e.g. receipts[1].amount
   */
  field: string;
  message?: string;
}
