/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FirstApprover } from './first-approver';

/**
 * Each possible value of `FirstApprover`
 */
export const FIRST_APPROVER: FirstApprover[] = [
  'LINE_MANAGER',
  'DEPARTMENT_MANAGER'
];