/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Job {
  errorCode?: (string | null);
  id: string;
  processed?: (number | null);
  status: 'QUEUED' | 'RUNNING' | 'SUCCEEDED' | 'FAILED';
  total?: (number | null);
  type: 'TENANT_PROVISIONING' | 'EMPLOYEE_IMPORT' | 'SETTLEMENT_EXPORT';
  updatedAt: string;
}
