/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TenantContext } from '../models/tenant-context';
import { TenantMembership } from '../models/tenant-membership';
export interface Me {
  displayName: string;
  email?: string;
  locale?: 'ar' | 'en';
  memberships: Array<TenantMembership>;
  permissions: Array<string>;
  tenant: TenantContext;
  userId: string;
}
