/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Organization {
  currency: string;
  defaultLocale: 'ar' | 'en';
  displayName: string;
  legalName: string;
  timezone: string;
  version: number;
}
