/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PageMetadata {

  /**
   * Zero-based page index
   */
  number: number;
  size: number;
  totalElements: number;
  totalPages: number;
}
