/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentEvidenceWrite } from '../models/payment-evidence-write';
export type PaymentEvidence = PaymentEvidenceWrite & {
'recordedBy': string;
'recordedAt': string;
};

