/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentMethod } from '../models/payment-method';
export interface PaymentEvidenceWrite {
  method: PaymentMethod;
  note?: (string | null);
  paidOn: string;

  /**
   * Bank or payroll reference
   */
  reference: string;
}
