/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Money } from '../models/money';
import { TransportMode } from '../models/transport-mode';
export interface PolicyWrite {
  allowedModes: Array<TransportMode>;
  currency: string;

  /**
   * Applies to trips on or after this calendar day
   */
  effectiveFrom: string;

  /**
   * Empty means every department
   */
  eligibleDepartmentIds?: Array<string>;
  monthlyLimit: Money;
  name: string;
  perTripLimit: Money;
  receiptRequiredAbove: Money;

  /**
   * Days after the claim month ends
   */
  submissionDeadlineDays: number;
}
