/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PolicyStatus } from '../models/policy-status';
import { PolicyWrite } from '../models/policy-write';
export type Policy = PolicyWrite & {
'id': string;
'status': PolicyStatus;

/**
 * Policy version number shown to users
 */
'version': number;

/**
 * Concurrency revision behind the ETag
 */
'rev': number;
'publishedAt'?: (string | null);
};

