/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PolicyFinding {

  /**
   * Stable code; UI text comes from translations
   */
  code: string;

  /**
   * Line the finding refers to, if any
   */
  itemIndex?: (number | null);
  params?: {
[key: string]: string;
};
  severity: 'INFO' | 'WARNING' | 'BLOCKING';
}
