/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PolicyStatus } from '../models/policy-status';
export interface PolicySummary {
  effectiveFrom: string;
  id: string;
  name: string;
  status: PolicyStatus;

  /**
   * Policy version number shown to users
   */
  version: number;
}
