/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PolicyStatus } from './policy-status';

/**
 * Each possible value of `PolicyStatus`
 */
export const POLICY_STATUS: PolicyStatus[] = [
  'DRAFT',
  'PUBLISHED',
  'RETIRED'
];