/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FieldError } from '../models/field-error';

/**
 * RFC 9457 ProblemDetail with TCMS extensions (D8)
 */
export interface Problem {

  /**
   * Stable machine-readable error code
   */
  code: string;
  detail?: string;
  fieldErrors?: Array<FieldError>;
  instance?: string;
  status: number;
  title?: string;
  traceId?: string;
  type?: string;
}
