/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScanStatus } from '../models/scan-status';
export interface Receipt {
  contentType: string;

  /**
   * Same file already on another claim; for review, never auto-removed
   */
  duplicateOfClaimNumber?: (string | null);
  fileName: string;
  id: string;

  /**
   * e.g. MALWARE_DETECTED, CONTENT_TYPE_MISMATCH
   */
  rejectionCode?: (string | null);
  scanStatus: ScanStatus;
  sizeBytes: number;
  uploadedAt: string;
}
