/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReceiptUploadSlot {
  expiresAt: string;

  /**
   * Headers the upload must send exactly (e.g. Content-Type)
   */
  headers: {
[key: string]: string;
};
  method: 'PUT';
  receiptId: string;

  /**
   * Presigned object-storage URL
   */
  uploadUrl: string;
}
