/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Role {

  /**
   * Stable key, e.g. EMPLOYEE, APPROVER; UI label comes from translations
   */
  key: string;
  permissions: Array<string>;
}
