/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScanStatus } from './scan-status';

/**
 * Each possible value of `ScanStatus`
 */
export const SCAN_STATUS: ScanStatus[] = [
  'AWAITING_UPLOAD',
  'SCANNING',
  'CLEAN',
  'REJECTED'
];