/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageMetadata } from '../models/page-metadata';
import { SettlementCandidate } from '../models/settlement-candidate';
export interface SettlementCandidatePage {
  content: Array<SettlementCandidate>;
  page: PageMetadata;
}
