/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageMetadata } from '../models/page-metadata';
import { SettlementBatchSummary } from '../models/settlement-batch-summary';
export interface SettlementBatchSummaryPage {
  content: Array<SettlementBatchSummary>;
  page: PageMetadata;
}
