/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettlementExport {
  createdAt: string;
  expiresAt?: (string | null);
  fileName: string;
  format: 'CSV' | 'XLSX';
  id: string;
}
