/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentEvidence } from '../models/payment-evidence';
import { SettlementBatchSummary } from '../models/settlement-batch-summary';
import { SettlementCandidate } from '../models/settlement-candidate';
import { SettlementExport } from '../models/settlement-export';
export type SettlementBatch = SettlementBatchSummary & {
'claims': Array<SettlementCandidate>;
'exports': Array<SettlementExport>;

/**
 * Running export job, if any
 */
'exportJobId'?: (string | null);
'exportErrorCode'?: (string | null);
'payment'?: (PaymentEvidence | null);
'version': number;
};

