/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Money } from '../models/money';
export interface SettlementCandidate {
  approvedAt?: (string | null);
  claimId: string;
  claimNumber: string;
  claimantName: string;
  currency: string;
  period: string;
  totalAmount: Money;
}
