/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BatchStatus } from '../models/batch-status';
import { Money } from '../models/money';
export interface SettlementBatchSummary {
  claimCount: number;
  createdAt: string;
  currency: string;
  id: string;
  number: string;
  status: BatchStatus;
  totalAmount: Money;
}
