/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SetupStep } from '../models/setup-step';
export interface SetupStatus {
  ready: boolean;
  steps: Array<SetupStep>;
}
