/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SetupStep {
  key: 'ORGANIZATION' | 'ACCESS' | 'EMPLOYEE_SOURCE' | 'POLICY';
  status: 'DONE' | 'PENDING' | 'NOT_AVAILABLE';
}
