/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantContext {

  /**
   * ISO 4217 code
   */
  currency: string;
  displayName: string;
  id: string;

  /**
   * IANA timezone
   */
  timezone: string;
}
