/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageMetadata } from '../models/page-metadata';
import { Tenant } from '../models/tenant';
export interface TenantPage {
  content: Array<Tenant>;
  page: PageMetadata;
}
