/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TenantStatus } from '../models/tenant-status';
export interface Tenant {
  adminEmail: string;
  createdAt: string;
  currency?: string;
  displayName: string;

  /**
   * Support reference when status is FAILED
   */
  failureReference?: (string | null);
  id: string;
  legalName: string;
  provisioningJobId?: (string | null);
  status: TenantStatus;
  timezone?: string;
}
