/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TenantStatus } from './tenant-status';

/**
 * Each possible value of `TenantStatus`
 */
export const TENANT_STATUS: TenantStatus[] = [
  'PROVISIONING',
  'READY',
  'FAILED'
];