/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimelineEvent {
  actorName?: (string | null);
  at: string;
  note?: (string | null);
  type: 'CREATED' | 'SUBMITTED' | 'CHANGES_REQUESTED' | 'RESUBMITTED' | 'APPROVED' | 'REJECTED' | 'EXPORTED' | 'SETTLED';
}
