/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransportMode } from './transport-mode';

/**
 * Each possible value of `TransportMode`
 */
export const TRANSPORT_MODE: TransportMode[] = [
  'TAXI',
  'RIDE_HAILING',
  'BUS',
  'METRO',
  'PERSONAL_CAR',
  'OTHER'
];