/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageMetadata } from '../models/page-metadata';
import { User } from '../models/user';
export interface UserPage {
  content: Array<User>;
  page: PageMetadata;
}
