/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserStatus } from '../models/user-status';
export interface User {
  displayName: string;
  email: string;
  employeeId?: (string | null);
  id: string;
  roles: Array<string>;
  status: UserStatus;
  version: number;
}
