/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserStatus } from './user-status';

/**
 * Each possible value of `UserStatus`
 */
export const USER_STATUS: UserStatus[] = [
  'ACTIVE',
  'INVITED',
  'DISABLED'
];