/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Policy } from '../../models/policy';

export interface CreatePolicyVersion$Params {
  policyId: string;

/**
 * Stable per user intent; reused on retry of the same intent
 */
  'Idempotency-Key': string;
}

export function createPolicyVersion(http: HttpClient, rootUrl: string, params: CreatePolicyVersion$Params, context?: HttpContext): Observable<StrictHttpResponse<Policy>> {
  const rb = new RequestBuilder(rootUrl, createPolicyVersion.PATH, 'post');
  if (params) {
    rb.path('policyId', params.policyId, {});
    rb.header('Idempotency-Key', params['Idempotency-Key'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Policy>;
    })
  );
}

createPolicyVersion.PATH = '/v1/policies/{policyId}/new-version';
