/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Policy } from '../../models/policy';
import { PolicyWrite } from '../../models/policy-write';

export interface UpdatePolicy$Params {
  policyId: string;

/**
 * ETag from the last read; stale values get 412
 */
  'If-Match': string;
      body: PolicyWrite
}

export function updatePolicy(http: HttpClient, rootUrl: string, params: UpdatePolicy$Params, context?: HttpContext): Observable<StrictHttpResponse<Policy>> {
  const rb = new RequestBuilder(rootUrl, updatePolicy.PATH, 'put');
  if (params) {
    rb.path('policyId', params.policyId, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Policy>;
    })
  );
}

updatePolicy.PATH = '/v1/policies/{policyId}';
